"""Deterministic generators for the derived files (invariant I3, rules GE-1 … GE-32).

Exactly three derived artifacts exist and this package is the only code that produces their content
(GE-1): the root ``index.md`` catalog, the root ``tags.md`` registry, and one ``index.md`` per topic
root. Everything else in the knowledge base is written by a human or an agent.

The contract every generator keeps, and why each half matters:

* **Wholesale replacement.** A derived file is truncated and replaced; its prior content is never
  read except to compare bytes (GE-2, GE-8). There is no version control (arch D6), so merging
  someone's hand edit into generated output would create a file nobody can reconstruct.
* **Never derived-as-input.** Tags rendered *inside* ``tags.md`` are output, not evidence of use
  (GE-3). Deleting every derived file and regenerating is the recovery mechanism, and it only works
  if the output does not depend on itself.
* **Byte-determinism.** No timestamp, no run id, no host, no version, no count (GE-6); every
  ordering has an explicit sort key (GE-4). The same tree renders the same bytes from any directory,
  under any hash seed, in any timezone — so a flush that changed nothing writes nothing (GE-5).
* **Total over a degraded tree.** A missing description renders a placeholder plus a diagnostic; a
  topic without a readable ``topic.md`` still gets its catalog line (GE-25). A file that is dropped
  from an index is invisible to every depth agent, which is a worse failure than an ugly line.

Rendering and writing are separate everywhere (GE-9): ``render_*`` is pure and takes a
:class:`~pkb.core.models.KbSnapshot`, ``generate_*`` renders and writes, and golden tests target the
pure half.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable, Sequence
from functools import partial
from pathlib import Path

from pkb.core import paths
from pkb.core.analysis import find_broken_links, find_orphans
from pkb.core.errors import Finding, Severity, sort_findings
from pkb.core.generators.base import (
    GENERATED_BANNER,
    inline,
    write_derived,
)
from pkb.core.generators.derive import cross_topic_pairs
from pkb.core.generators.root_index import (
    generate_root_index,
    render_root_index,
    root_index_findings,
)
from pkb.core.generators.tags_registry import (
    generate_root_tags,
    render_root_tags,
    root_tags_findings,
)
from pkb.core.generators.topic_index import (
    generate_topic_index,
    render_topic_index,
    topic_index_findings,
)
from pkb.core.models import FlushReport, KbSnapshot, TopicRecord
from pkb.core.scan import scan

__all__ = [
    "GENERATED_BANNER",
    "cross_topic_pairs",
    "flags_for_topic",
    "generate_root_index",
    "generate_root_tags",
    "generate_topic_index",
    "inline",
    "regenerate_all",
    "render_root_index",
    "render_root_tags",
    "render_topic_index",
    "root_index_findings",
    "root_tags_findings",
    "topic_index_findings",
    "write_derived",
]


def regenerate_all(
    kb_root: Path,
    *,
    snapshot: KbSnapshot | None = None,
    flags: Sequence[Finding] | None = None,
) -> FlushReport:
    """Rewrite every derived file and report what changed (GE-30, GE-5, GE-28).

    The single public entry point for generation. It assumes it is the **sole writer** for its
    duration and acquires no lock of its own — the global knowledge-base write lock belongs to
    Layer 2's ``after_agent`` middleware (MA-15, Q16). It is safe to call repeatedly and safe to
    call after a partial or failed agent run (MA-14): nothing it writes depends on the previous
    state of what it writes.

    The derived set is exactly ``{<kb>/index.md, <kb>/tags.md, <topic root>/index.md per topic}``
    (GE-28, PA-12). An ``index.md`` that is derived by *name* but generated by nobody — a stale
    ``notes/x/index.md`` — is never written and never deleted here; it is reported instead, by
    validation when it shadows an item (VA-17) and by the orphan pass as a stale file (PA-12).

    ``flags`` is a flat sequence of maintenance findings, routed to the topic index that owns each
    one by its path (MA-10); a section with nothing in it is omitted, which is how a fixed defect
    clears itself on the next run. Left as ``None`` — which is what a bare rebuild and
    ``scaffold_topic``'s SC-7 call do — the flags are **derived from the tree** here.

    That derivation is GE-5, not a convenience. A derived file must be a function of the tree and
    not of who called: while the flags arrived only from outside, a flush wrote the
    ``## Maintenance flags`` section and the next bare rebuild silently stripped it back out, so
    creating one topic rewrote the index of every other one and CX-4's "delete every derived file
    and rebuild byte-identically" was false for any knowledge base with a defect in it.
    :func:`~pkb.core.maintenance.flush` passes the list it already computed, so nothing is analysed
    twice; an explicit ``()`` is the opt-out a renderer test uses to pin the empty-section shape.

    Takes no clock. Derived files carry no dates at all (GE-6), which is what makes a second
    consecutive call report zero files written.

    The returned ``findings`` are the **generators'** diagnostics only — degraded entries and
    unrenderable ``related_topics`` (GE-25, GE-19) — plus any write failure. ``snapshot.findings``
    (walk-time defects, VA-39) are deliberately not folded in, so a caller that already reports them
    does not report them twice; ``maintenance.flush`` should merge the two lists itself. The flags
    are not folded in either, derived here or not: rendering them into the tree is generation, but
    *reporting* them is the flush's duty (MA-13), and one defect must not arrive twice (CX-5).
    """
    snap = scan(kb_root) if snapshot is None else snapshot
    if flags is None:
        flags = [*find_broken_links(kb_root, snap), *find_orphans(kb_root, snap)]
    report = FlushReport()

    _write(report, paths.INDEX_FILE, partial(generate_root_index, kb_root, snap))
    _write(report, paths.TAGS_FILE, partial(generate_root_tags, kb_root, snap))
    for topic in snap.topics.values():
        _write(
            report,
            f"{topic.path}/{paths.INDEX_FILE}",
            partial(
                generate_topic_index,
                kb_root,
                snap,
                topic.path,
                flags_for_topic(snap, topic, flags),
            ),
        )

    findings: list[Finding] = [
        *report.findings,
        *root_index_findings(snap),
        *root_tags_findings(snap),
    ]
    for topic in snap.topics.values():
        findings += topic_index_findings(snap, topic.path)
    report.findings = sort_findings(dict.fromkeys(findings))
    return report


def _write(report: FlushReport, relative: str, action: Callable[[], bool]) -> None:
    """Run one generator, recording the outcome instead of letting an OSError abort the flush.

    A directory that cannot be written is a deployment problem, not a content defect, but the flush
    must still regenerate everything it *can* (MA-14) — a single unwritable topic must not leave the
    root catalog stale.

    A case-variant collision is reported under its own code: the human's fix is to rename a file,
    which no amount of checking directory permissions will suggest (PA-17).
    """
    try:
        changed = action()
    except FileExistsError as exc:
        report.findings.append(
            Finding(
                code="DERIVED_NAME_CASE_COLLISION",
                severity=Severity.ERROR,
                message=f"the derived file was not written: {exc}",
                rule_id="PA-17",
                path=relative,
                hint=(
                    "an authored file already holds this name under a different case; rename it, "
                    "because writing here would destroy it"
                ),
            )
        )
        return
    except OSError as exc:
        report.findings.append(
            Finding(
                code="DERIVED_WRITE_FAILED",
                severity=Severity.ERROR,
                message=f"the derived file could not be written: {exc}",
                rule_id="GE-8",
                path=relative,
                hint="check the directory exists and is writable",
            )
        )
        return
    (report.written if changed else report.unchanged).append(relative)


def flags_for_topic(
    snapshot: KbSnapshot, topic: TopicRecord, flags: Iterable[Finding]
) -> list[Finding]:
    """The subset of ``flags`` that belongs in one topic's index (MA-10).

    A finding belongs to the **nearest** owning topic root, so a defect inside
    ``Cooking/sub-topics/Grilling/notes/`` is flagged in Grilling's index and not in Cooking's —
    otherwise every ancestor would repeat every descendant's flags and the section would grow with
    depth. Findings with no path, or a path outside every topic, are report-only (MA-10, v1).
    """
    prefix = f"{topic.path}/"
    owned: list[Finding] = []
    for finding in flags:
        if finding.path is None or not finding.path.startswith(prefix):
            continue
        nearest = _owning_topic(snapshot, finding.path)
        if nearest == topic.path:
            owned.append(finding)
    return owned


def _owning_topic(snapshot: KbSnapshot, path: str) -> str | None:
    """The longest topic-root prefix of a KB-relative path (PA-15, over the snapshot)."""
    best: str | None = None
    for candidate in snapshot.topics:
        if path.startswith(f"{candidate}/") and (best is None or len(candidate) > len(best)):
            best = candidate
    return best
