"""The byte-level primitives all three generators share (GE-2, GE-7, GE-8, GE-9, GE-26).

Nothing here decides *what* a derived file says; it decides how the bytes are shaped and how they
reach the disk. Keeping that in one module is what makes GE-7's format lint a single assertion
rather than three, and what lets every ``render_*`` function stay pure (GE-9): the renderers build
a list of lines, this module turns lines into a document, and exactly one function writes.

The document shape is fixed:

.. code-block:: text

    ---                     <- canonical frontmatter (FM-7, FM-8, FM-12)
    ...
    ---
                            <- one blank line
    # Heading
                            <- one blank line
    <!-- banner -->         <- index files only; the README pins tags.md without it
                            <- one blank line before every section heading
    ## Section

Sections are omitted entirely when their body is empty (§4.3), which :func:`section` enforces by
returning no lines at all rather than an empty block.
"""

from __future__ import annotations

import os
import re
import tempfile
from collections.abc import Iterable
from pathlib import Path

from pkb.core import frontmatter, paths
from pkb.core.errors import Finding, Severity
from pkb.core.models import Metadata

__all__ = [
    "EM_DASH",
    "GENERATED_BANNER",
    "MIDDLE_DOT",
    "MISSING_TOPIC_METADATA",
    "NO_DESCRIPTION",
    "TAGS_PREFIX",
    "document",
    "inline",
    "item_bullet",
    "missing_description",
    "missing_topic_metadata",
    "render_lines",
    "section",
    "write_derived",
]

GENERATED_BANNER = (
    "<!-- Generated by pkb.core. Do not edit: this file is overwritten on every flush. -->"
)
"""The "do not edit" line carried by both generated ``index.md`` files (§4.2, §4.3).

Root ``tags.md`` does **not** carry it: README §1.5 pins that file's first lines verbatim and the
banner is not among them (GE-21).
"""

EM_DASH = " \u2014 "
"""EM DASH with single spaces, before an entry's description (§4.2, §4.3).

Written as an escape, like every significant glyph in this package, so a diff, a review, or an
editor's autocorrect cannot quietly swap it for a hyphen and fail a golden test on invisible bytes.
"""

MIDDLE_DOT = "\u00b7"
"""MIDDLE DOT: reserved as the item-bullet separator, so :func:`inline` strips it from text."""

TAGS_PREFIX = f" {MIDDLE_DOT} tags: "
"""Introduces an item bullet's tag list (§4.3)."""

NO_DESCRIPTION = "*(no description)*"
"""Rendered in place of a missing, empty or unparseable ``description`` (GE-25)."""

MISSING_TOPIC_METADATA = "*(missing topic metadata)*"
"""Rendered for a topic root whose ``topic.md`` is missing or unparseable (GE-25)."""

_WHITESPACE = re.compile(r"\s+")


# --------------------------------------------------------------------------------------
# Degraded-entry diagnostics (GE-25)
# --------------------------------------------------------------------------------------


def missing_description(path: str) -> Finding:
    """The diagnostic that accompanies a :data:`NO_DESCRIPTION` placeholder (GE-25).

    Warning rather than error: the entry *was* rendered, the flush completed, and Layer 2 must not
    read a degraded index line as a reason to reject the next write (MA-9). Validation reports the
    same file's missing field at error severity on the write path, where blocking is the right
    answer.
    """
    return Finding(
        code="MISSING_DESCRIPTION",
        severity=Severity.WARNING,
        message="no usable description, so the index renders a placeholder for this entry",
        rule_id="GE-25",
        path=path,
        field="description",
        hint="add a single-line description to the file's frontmatter",
    )


def missing_topic_metadata(path: str) -> Finding:
    """The diagnostic that accompanies a :data:`MISSING_TOPIC_METADATA` placeholder (GE-25)."""
    return Finding(
        code="MISSING_TOPIC_METADATA",
        severity=Severity.WARNING,
        message=(
            "this topic root has no readable topic.md, so its catalog entry falls back to the "
            "folder name and carries no description"
        ),
        rule_id="GE-25",
        path=path,
        hint="add a topic.md carrying the seven required fields",
    )


# --------------------------------------------------------------------------------------
# Text (GE-26)
# --------------------------------------------------------------------------------------


def inline(text: str) -> str:
    """Make arbitrary authored text safe to drop into one markdown line (GE-26).

    Collapses every whitespace run — newlines included — to a single space and strips, replaces the
    reserved :data:`MIDDLE_DOT` so a description cannot fake the ``· tags:`` affordance, and escapes
    ``\\``, ``[`` and ``]`` so a bracketed phrase in a title cannot break out of its link.

    The backslash is escaped **first**, and that order is load-bearing in both directions. An
    escaper that ignores its own escape character is not one: a title ending in ``\\`` meets the
    closing ``]`` that :func:`item_bullet` appends and yields ``\\]``, which CommonMark reads as a
    literal bracket — the link text never closes, the bullet renders as prose, and GE-26's stated
    acceptance criterion (a markdown-parser round-trip without structural change) fails. Escaping
    after the brackets would instead double-escape the ``\\[``/``\\]`` this function just produced.

    Values are never truncated: an index entry is how a depth agent decides whether to open a file,
    and a clipped description makes that decision on false evidence.
    """
    collapsed = _WHITESPACE.sub(" ", text).strip()
    without_dot = collapsed.replace(MIDDLE_DOT, "-")
    escaped = without_dot.replace("\\", "\\\\")
    return escaped.replace("[", "\\[").replace("]", "\\]")


def item_bullet(text: str, target: str, gloss: str, suffix: str = "") -> str:
    """One linked list item: ``- [text](target) — gloss<suffix>`` (§4.2, §4.3).

    ``text`` and ``gloss`` must already have passed through :func:`inline`; ``target`` must already
    be a relative, percent-encoded link (PA-18). Kept in one place so the three generators cannot
    drift on a space.
    """
    return f"- [{text}]({target}){EM_DASH}{gloss}{suffix}"


# --------------------------------------------------------------------------------------
# Document assembly (GE-7)
# --------------------------------------------------------------------------------------


def section(title: str, body: Iterable[str]) -> list[str]:
    """A ``## title`` block, or **no lines at all** when the body is empty (§4.3).

    Every section of every derived file is omitted rather than rendered empty, so a topic with no
    references does not carry a heading promising some.
    """
    lines = list(body)
    if not lines:
        return []
    return ["", f"## {title}", "", *lines]


def document(meta: Metadata, heading: str, blocks: Iterable[str], *, banner: bool = True) -> str:
    """Assemble a whole derived file: frontmatter, H1, optional banner, then sections (GE-7).

    ``meta`` is rendered by :func:`pkb.core.frontmatter.serialize`, so derived frontmatter obeys the
    same canonical order and style as authored frontmatter (FM-7, FM-8) while carrying only the
    minimal generated key set (FM-12).
    """
    front = frontmatter.serialize(meta, "").split("\n")[:-1]
    lines = [*front, "", f"# {heading}"]
    if banner:
        lines += ["", GENERATED_BANNER]
    lines += list(blocks)
    return render_lines(lines)


def render_lines(lines: Iterable[str]) -> str:
    """Join rendered lines into the derived byte format (GE-7).

    UTF-8 (the caller's encoding step), LF endings, exactly one trailing newline, no trailing blank
    line. Trailing whitespace and tabs are the renderers' responsibility — the format test in
    ``tests/core/test_generators.py`` asserts every generated file against all of GE-7.
    """
    kept = list(lines)
    while kept and not kept[-1]:
        kept.pop()
    return "".join(f"{line}\n" for line in kept)


# --------------------------------------------------------------------------------------
# Writing (GE-2, GE-8, PA-17)
# --------------------------------------------------------------------------------------


def _refuse_case_variant(path: Path) -> None:
    """Raise when ``path`` resolves onto a directory entry spelled with a different case (PA-17).

    The development host is case-insensitive APFS, so an authored ``Cooking/INDEX.md`` *is* the
    kernel's answer for ``Cooking/index.md``. Without this check :meth:`Path.replace` truncates the
    human's file in place, leaves it under its original name, and the flush cheerfully reports
    having written a path that still does not exist. Nothing else in Layer 1 catches it: the file
    is not :func:`~pkb.core.paths.is_derived_name`, so validation calls it authored content and
    warns rather than removes it (VA-38), and with no version control (arch D6, CX-4) the prose is
    unrecoverable. That is §5's "never overwrite human content" and MA-5's "the body must survive a
    flush untouched", broken silently — hence a guard rather than a comment.

    **Why an exception and not a Finding.** MA-14 forbids a *flush* that aborts; it does not forbid
    a primitive that raises. Both callers of :func:`write_derived` already translate
    :class:`OSError` into a finding and carry on — ``generators._write`` into
    ``DERIVED_WRITE_FAILED`` (GE-8) and ``maintenance._bump_updated`` into ``UPDATED_WRITE_FAILED``
    (MA-3) — so every other derived file is still regenerated and the defect is reported, which is
    exactly MA-9's non-blocking, non-mutating contract. The ``bool`` :func:`write_derived` returns
    cannot carry the refusal either: ``True`` would claim a write that did not happen and ``False``
    would claim the bytes already matched, and its signature is pinned by the rules appendix. The
    check runs *before* the byte compare so a collided file that happens to already hold this
    render's bytes is reported rather than silently accepted.

    Cost and scope: one ``scandir`` per derived write. On a case-sensitive host ``path.exists()``
    is False while only the variant is present, so the generator creates its own file as usual and
    the guard never fires. One deliberate consequence beyond the generators: a mis-cased path in
    Layer 2's touched set (``notes/Steak.md`` for an on-disk ``notes/steak.md``) now yields a
    finding from ``maintenance._stamp`` instead of stamping the differently-cased file — a
    behaviour change, and the safer of the two answers.
    """
    if not paths.has_case_exact_entry(path.parent, path.name) and path.exists():
        raise FileExistsError(
            f"refusing to write {path.name!r}: {path.parent} already holds that name under a "
            "different case, and replacing it would destroy the existing file (PA-17)"
        )


def write_derived(path: Path, text: str) -> bool:
    """Replace ``path`` with ``text`` atomically, skipping an identical write (GE-2, GE-8, PA-17).

    Returns True when the bytes on disk changed. The existing file is read **only** to compare
    bytes — never merged, never partially preserved (GE-2), because prior content is by definition
    either this generator's own output or something that should not be there.

    Skipping an identical write is what makes a no-op flush leave every ``st_mtime_ns`` untouched,
    which in turn is what lets a caller trust "zero files written" as a real answer (GE-5).

    The write goes to a temp file in the *same* directory and lands with :meth:`Path.replace`, so a
    reader never observes a half-written index: on POSIX the rename is atomic within a filesystem,
    and a temp file elsewhere would cross one. Raises :class:`OSError` when the directory is not
    writable, or when the target name collides with a case variant already on disk
    (:func:`_refuse_case_variant`); the caller decides whether that aborts the flush
    (:func:`regenerate_all` does not).
    """
    _refuse_case_variant(path)
    data = text.encode("utf-8")
    try:
        if path.read_bytes() == data:
            return False
    except OSError:
        pass  # missing, unreadable, or a directory — all mean "the bytes differ"

    path.parent.mkdir(parents=True, exist_ok=True)
    handle, name = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    os.close(handle)
    temp = Path(name)
    try:
        temp.write_bytes(data)
        temp.replace(path)
    except BaseException:
        temp.unlink(missing_ok=True)
        raise
    return True
